/* scan.js - V0.9.6 - module EAN, statuts, contenu et photo objet */
/* Charger APRES app.js. Ne modifie ni ui.js ni app.js. */
(function(){
"use strict";
function has(s,sub){return String(s||"").toLowerCase().indexOf(String(sub||"").toLowerCase())>=0;}
function clean(s){s=String(s||"").split("\n").join(" ").split("\r").join(" ").split("\t").join(" ");while(s.indexOf("  ")>=0)s=s.split("  ").join(" ");return s.trim();}
function meta(doc,p){var n=doc.querySelector('meta[property="'+p+'"]')||doc.querySelector('meta[name="'+p+'"]');return n?clean(n.getAttribute("content")||""):"";}
function isDigits(s){if(!s)return false;for(var i=0;i<s.length;i++){if(s.charAt(i)<"0"||s.charAt(i)>"9")return false;}return true;}
function extractYear(t){var s=String(t||"");for(var i=0;i+4<s.length;i++){if(s.charAt(i)==="("&&isDigits(s.substring(i+1,i+5))&&s.charAt(i+5)===")")return s.substring(i+1,i+5);}return "";}
function stripYear(t){var y=extractYear(t);if(!y)return clean(t);var i=t.indexOf("("+y+")");if(i<0)return clean(t);return clean(t.substring(0,i));}
function pick(list,key){for(var i=0;i<list.length;i++){if(list[i][key])return list[i][key];}return "";}
function detectPackaging(t){if(has(t,"steelbook")||has(t,"steel book")||has(t,"boitier metal")||has(t,"boîtier métal"))return "Steelbook";if(has(t,"digipack")||has(t,"digipak"))return "Digipack";if(has(t,"coffret"))return "Coffret";return "";}
function detectSupport(t){if(has(t,"4k ultra hd")||has(t,"uhd"))return "Physique - 4K UHD";if(has(t,"blu-ray")||has(t,"bluray"))return "Physique - Blu-ray";if(has(t,"dvd"))return "Physique - DVD";return "Physique";}
function sectionAfter(doc,label){var hs=doc.querySelectorAll("h1,h2,h3,h4");for(var i=0;i<hs.length;i++){if(has(hs[i].textContent,label)){var out=[],n=hs[i].nextElementSibling;while(n&&n.tagName.indexOf("H")!==0){out.push(clean(n.textContent));n=n.nextElementSibling;}var s=out.join(" ").trim();if(s)return s;}}return "";}
async function searchDVDFR(ean){var u="https://www.dvdfr.com/dvd/"+ean+"/";var h=await urlFetchHTML(u);if(!h)return null;var doc=new DOMParser().parseFromString(h,"text/html");var t=meta(doc,"og:title")||clean((doc.querySelector("h1")||{}).textContent||"");if(!t)return null;var blob=t+" "+h.slice(0,30000);var img=meta(doc,"og:image");if(!img){var im=doc.querySelector("img[src*='epagine']")||doc.querySelector("img[src*='couvert']")||doc.querySelector("img[src*='media']");if(im)img=im.getAttribute("src")||"";}return{source:"dvdfr",title:t,year:extractYear(t),imageUrl:img,productUrl:u,contenu:sectionAfter(doc,"contenu et bonus")||clean((doc.querySelector(".description.scrollbar-style")||{}).textContent||""),packaging:detectPackaging(blob),support:detectSupport(blob)};}
async function searchAmazon(ean){var u="https://www.amazon.fr/dp/"+ean;var h=await urlFetchHTML(u);if(!h)return null;var doc=new DOMParser().parseFromString(h,"text/html");var t=meta(doc,"og:title");if(!t)return null;var img=meta(doc,"og:image");var contenu=clean((doc.querySelector("#productDescription")||{}).textContent||"");var blob=t+" "+h.slice(0,30000);return{source:"amazon",title:t,year:extractYear(t),imageUrl:img,productUrl:u,contenu:contenu,packaging:detectPackaging(blob),support:detectSupport(blob)};}
async function searchFnac(ean){var u="https://recherche.fnac.com/SearchResult/ResultList.aspx?Search="+ean;var h=await urlFetchHTML(u);if(!h)return null;var doc=new DOMParser().parseFromString(h,"text/html");var card=doc.querySelector(".f-productCard")||doc.querySelector("article")||doc.querySelector(".product-card");if(!card)return null;var a=card.querySelector("a");var t=clean((card.querySelector(".f-productCard-title")||card.querySelector("h3")||card.querySelector("h2")||{}).textContent||"");if(!t&&a)t=clean(a.getAttribute("title")||"");if(!t)return null;var im=card.querySelector("img");var img=im?(im.getAttribute("src")||im.getAttribute("data-src")||""):"";var pu=a?(a.getAttribute("href")||""):"";if(pu&&pu.indexOf("http")!==0)pu="https://www.fnac.com"+pu;return{source:"fnac",title:t,year:extractYear(t),imageUrl:img,productUrl:pu,contenu:"",packaging:"",support:"Physique"};}
function openStatusSheet3(e,cb){var s={isEnc:!!e.enCours,isVoir:!!e.aVoir,isFini:!!e.fini};var b=el("div","chips");var chips=[];function paint(){for(var i=0;i<chips.length;i++){chips[i][1].classList.toggle("on",!!s[chips[i][0]]);}}function mk(k,l,i){var c=el("div","chip"+(s[k]?" on":""),'<span class="ic">'+ic(i)+"</span><span>"+l+"</span>");c.addEventListener("click",function(){s[k]=!s[k];if(s[k]&&k==="isFini"){s.isEnc=false;s.isVoir=false;}if(s[k]&&k!=="isFini"){s.isFini=false;}paint();});chips.push([k,c]);b.appendChild(c);}mk("isEnc","En cours","hourglass");mk("isVoir","À voir","eye");mk("isFini","Vu / Fini","check");setSheet("Statuts",b,[["Valider","primary",function(){cb({isEnc:s.isEnc,isVoir:s.isVoir,isFini:s.isFini});closeMenu();},"check"],["Annuler","",closeMenu,"x"]]);}
function openContenuSheet(text,cb){var b=el("div");var ta=el("textarea");ta.value=text||"";ta.style.minHeight="260px";ta.readOnly=true;var eb=btn("Modifier le contenu","pen","wide",function(){ta.readOnly=false;ta.focus();eb.style.display="none";});b.appendChild(ta);b.appendChild(eb);setSheet("Contenu et bonus",b,[["Valider","primary",function(){cb(ta.value.trim());closeMenu();},"check"],["Fermer","",closeMenu,"x"]]);}
function openImageUrlSheet(e,cb){var b=el("div"),ip=el("input");ip.placeholder="https://…";ip.value=e.imageUrl||"";b.appendChild(ip);var fi=el("input");fi.type="file";fi.accept="image/*";fi.hidden=true;var bi=btn("Importer une photo","folder","wide",function(){fi.click();});fi.addEventListener("change",function(ev){var f=ev.target.files[0];if(f)fileToResized(f,600).then(function(u){ip.value=u;});});b.appendChild(bi);b.appendChild(fi);setSheet("Photo de l'objet",b,[["Valider","primary",function(){cb(ip.value.trim());closeMenu();},"check"],["Annuler","",closeMenu,"x"]]);}
function openImageMenu(e,cb){var b=el("div");b.appendChild(btn("Voir la photo","maximize-2","wide",function(){closeMenu();openPosterZoom(e.imageUrl);}));b.appendChild(btn("Remplacer","pen","wide",function(){closeMenu();openImageUrlSheet(e,cb);}));b.appendChild(btn("Retirer","trash","wide",function(){closeMenu();cb("");}));setSheet("Photo de l'objet",b,[["Annuler","",closeMenu,"x"]]);}
async function searchFromEAN(ean){var st=$("search-status");if(st){st.className="status";st.textContent="Recherche du code "+ean+"…";}var dvd=null,ama=null,fna=null;try{dvd=await searchDVDFR(ean);}catch(err){dvd=null;}try{ama=await searchAmazon(ean);}catch(err){ama=null;}try{fna=await searchFnac(ean);}catch(err){fna=null;}var order=[];if(dvd)order.push(dvd);if(ama)order.push(ama);if(fna)order.push(fna);if(!order.length){if(st)st.textContent="";toast("Aucune info trouvée pour ce code.",3000);return;}var title=pick(order,"title");var imageUrl=pick(order,"imageUrl");var productUrl=pick(order,"productUrl");var contenu=pick(order,"contenu");var packaging=pick(order,"packaging");var support=pick(order,"support")||"Physique";var poster="";var ct=stripYear(title);if(ct){try{var r=await searchTMDB(ct,"movie");if(r&&r.length&&r[0].poster)poster=r[0].poster;}catch(err){poster="";}}var existing=null;for(var i=0;i<ST.entries.length;i++){if(ST.entries[i].ean===ean){existing=ST.entries[i];break;}}if(existing){if(st)st.textContent="";toast("EAN déjà dans ta bibliothèque");showCollectionDetail(existing);return;}var type=(ean.indexOf("978")===0||ean.indexOf("979")===0)?"Livre":"Film";var id=type+"_ean_"+ean;for(var k=0;k<ST.entries.length;k++){if(ST.entries[k].id===id){id=id+"_"+Date.now();break;}}var entry={id:id,type:type,titre:title||("EAN "+ean),sousTitre:"",note:null,coeur:false,enCours:false,aVoir:false,fini:false,inCollection:true,journal:[],posterUrl:poster,posterThumb:"",imageUrl:imageUrl,contenu:contenu,support:support,packaging:packaging,ean:ean,url:productUrl,plateforme:null,edition:null,bonus:[],dateFin:todayFR(),dateAchat:null,dateAjout:new Date().toISOString(),comment:"",tmdb_id:null};await dbPut(entry);await refreshAll();var saved=entry;for(var j=0;j<ST.entries.length;j++){if(ST.entries[j].id===id){saved=ST.entries[j];break;}}if(st)st.textContent="";toast("Fiche créée depuis le scan");showCollectionDetail(saved);}
var _scd=showCollectionDetail;
showCollectionDetail=function(e){_scd(e);var body=$("m-body");if(!body)return;var sb=body.querySelector('.adv-btn[data-k="statuts"]');if(sb){var nb=detailValueBtn("flag","Statuts","statuts",e.fini?"Fini":detailStatusLabel(e),function(){openStatusSheet3(e,function(st2){e.enCours=st2.isEnc;e.aVoir=st2.isVoir;e.fini=st2.isFini;dbPut(e).then(function(){toast("Statuts mis à jour");updateAdvBtn("statuts",st2.isFini?"Fini":statusText(st2));syncPoster(e);refreshAll();});});});sb.parentNode.replaceChild(nb,sb);}var ac=body.querySelector(".detail-actions");var fb=el("div","field");fb.appendChild(el("span","flabel","Médias et contenu"));var row=el("div","form-row");row.appendChild(detailValueBtn("image","Image objet","_img",e.imageUrl?"Voir":"",function(){if(e.imageUrl){openImageMenu(e,function(v){e.imageUrl=v;dbPut(e).then(function(){toast(v?"Photo mise à jour":"Photo retirée");updateAdvBtn("_img",v?"Voir":"");});});}else{openImageUrlSheet(e,function(v){e.imageUrl=v;dbPut(e).then(function(){toast("Photo enregistrée");updateAdvBtn("_img",v?"Voir":"");});});}}));row.appendChild(detailValueBtn("file-text","Contenu et bonus","_contenu",e.contenu?"Voir":"",function(){openContenuSheet(e.contenu||"",function(v){e.contenu=v;dbPut(e).then(function(){toast("Contenu mis à jour");updateAdvBtn("_contenu",v?"Voir":"");});});}));fb.appendChild(row);if(ac)body.insertBefore(fb,ac);else body.appendChild(fb);};
function injectBarcodeBtn(){if($("search-barcode"))return;var loupe=$("search-loupe");if(!loupe||!loupe.parentNode)return;var b=el("button","sq-btn");b.id="search-barcode";b.setAttribute("aria-label","Scanner un code-barres");b.innerHTML='<span class="ic">'+ic("barcode")+"</span>";b.addEventListener("click",function(){startEAN(function(code){searchFromEAN(code);});});loupe.parentNode.appendChild(b);}
injectBarcodeBtn();
})();