/* js/ui.js — V0.9.3 */
var ST={entries:[],view:"search",colQuery:"",calDate:new Date(),calSel:null,calMode:"journal",calPickCb:null,editing:null,selectedItem:null,currentType:"Film",panelType:"Film",currentNote:null,isCoeur:false,isEnc:false,isVoir:false,isInCollection:false,draftJournal:[],panelPoster:"",panelThumb:"",qnEntry:null,qnKind:"time",qnEditIdx:null,qnDest:null,pickerVal:null,recent:[],filterType:"all",filterSupport:"all",filterSort:{key:"date",dir:"desc"},advFields:{plateforme:"",dateAchat:"",edition:"",bonus:[],support:"",packaging:"",ean:"",url:""},draft:{titre:"",date:"",comment:"",sub:""},currentReaderEntry:null,currentReaderJournalIdx:null,lastJournalCount:0,searchToken:0,journalSheetRebuild:null};
var overlayStack=[],zCounter=0;
var KINDS=[["time","Note datée","calendar"],["free","Instantané","pen"],["ep","Épisode","tv"],["session","Session","timer"],["pages","Pages","file-text"]];
var COLOR_SWATCHES=["#B24BF3","#7F5AF0","#C0392B","#E74C3C","#F59E0B","#FFD700","#10B981","#2CB67D","#3B82F6","#06B6D4","#EC4899","#FF5DA2","#94A3B8","#8E44AD","#16A34A","#EA580C"];
var LUCIDE_NAMES=["film","tv","gamepad-2","book-open","image","scroll","disc","music","mic","headphones","monitor","smartphone","tablet","laptop","cpu","hard-drive","usb","battery","wifi","bluetooth","box","package","package-open","gift","tag","tags","bookmark","star","heart","thumb-up","clock","calendar","calendar-check","hourglass","timer","alarm-clock","history","pen","edit","pencil","file-text","notebook-pen","notebook","clipboard","clipboard-list","list","grid","layout-grid","layers","stack","archive","inbox","folder","folder-open","search","zoom-in","zoom-out","maximize-2","expand","eye","eye-off","lock","unlock","key","camera","image-plus","images","clapperboard","megaphone","radio","satellite","globe","map","map-pin","compass","navigation","anchor","ship","plane","train","car","bike","footprints","mountain","tree-pine","leaf","flower-2","sun","moon","cloud","droplets","flame","zap","sparkles","palette","brush","spray-can","wand-2","scissors","utensils","coffee","wine","beer","cake-slice","ice-cream","apple","cherry","grape","dumbbell","trophy","medal","flag","crown","gem","coins","banknote","wallet","credit-card","shopping-bag","shopping-cart","store","briefcase","backpack","graduation-cap","school","baby","users","user","smile","frown","ghost","mask","drama","theater","ticket","concert"];

function el(tag,cls,html){var d=document.createElement(tag);if(cls)d.className=cls;if(html!=null)d.innerHTML=html;return d;}
function $(id){return document.getElementById(id);}
function fieldBox(label,control){var d=el("div","field");d.appendChild(el("span","flabel",label));d.appendChild(control);return d;}
function btn(label,icon,cls,fn){var b=el("button",cls||"");var head=icon?'<span class="ic">'+ic(icon)+"</span>":"";b.innerHTML=head+"<span>"+esc(label)+"</span>";if(fn)b.addEventListener("click",fn);return b;}
function emptyBox(iconName,txt){var d=el("div","empty");d.innerHTML='<span class="ic">'+ic(iconName)+"</span>"+esc(txt);return d;}
function toast(msg,ms){var e=$("toast");if(!e)return;e.textContent=msg;e.classList.add("show");setTimeout(function(){e.classList.remove("show");},ms||1800);}
function valueIconHTML(item){var col=item&&item.color?item.color:"var(--acc)";return'<span class="ic" style="color:'+col+'">'+ic((item&&item.icon)||"tag")+"</span>";}
function burstHearts(button){if(document.body.dataset.anim==="off")return;for(var i=0;i<6;i++){var s=el("span","hb");s.innerHTML=ic("heart");var ang=(Math.PI*2/6)*i+Math.random()*0.4;var dist=26+Math.random()*16;s.style.setProperty("--dx",Math.cos(ang)*dist+"px");s.style.setProperty("--dy",Math.sin(ang)*dist+"px");s.style.animationDelay=(i*28)+"ms";button.appendChild(s);setTimeout(function(node){return function(){if(node.parentNode)node.remove();};}(s),900);}}
function makeHeartButton(on,onToggle){var b=el("button","heart-btn"+(on?" on":""));b.setAttribute("aria-label","Coup de cœur");b.innerHTML='<span class="ic">'+ic("heart")+"</span>";b.addEventListener("click",function(){var now=!b.classList.contains("on");b.classList.toggle("on",now);burstHearts(b);if(onToggle)onToggle(now);});return b;}

function showOverlay(id){var e=$(id);if(!e)return;zCounter++;e.style.zIndex=200+zCounter;e.classList.add("on");if(overlayStack.indexOf(id)<0)overlayStack.push(id);try{history.pushState(null,"");}catch(err){}}
function hideOverlay(id){var e=$(id);if(!e)return;e.classList.remove("on");var i=overlayStack.indexOf(id);if(i>=0)overlayStack.splice(i,1);}
window.addEventListener("popstate",function(){var id=overlayStack[overlayStack.length-1];if(id){var e=$(id);if(e)e.classList.remove("on");overlayStack.pop();}});
function closeModal(){hideOverlay("modal-overlay");var b=$("m-body");if(b)b.innerHTML="";var f=$("m-foot");if(f)f.innerHTML="";ST.editing=null;}
function closeReader(){hideOverlay("reader-overlay");ST.currentReaderEntry=null;ST.currentReaderJournalIdx=null;}
function closeMenu(){hideOverlay("menu-overlay");}
function setModal(title,bodyNode,foot){var t=$("m-title");if(t)t.textContent=title;var b=$("m-body");if(b){b.innerHTML="";b.appendChild(bodyNode);}var f=$("m-foot");if(f){f.innerHTML="";(foot||[]).forEach(function(bt){var node=el("button",bt[1]||"");var iconName=bt[3]||"";var head=iconName?'<span class="ic">'+ic(iconName)+"</span>":"";node.innerHTML=head+"<span>"+esc(bt[0])+"</span>";node.addEventListener("click",bt[2]);f.appendChild(node);});}showOverlay("modal-overlay");}
function setSheet(title,bodyNode,foot){var t=$("menu-title");if(t)t.textContent=title;var b=$("menu-body");if(!b)return;b.innerHTML="";b.appendChild(bodyNode);(foot||[]).forEach(function(bt){var node=el("button",(bt[1]||"")+" wide");node.style.marginTop="10px";var iconName=bt[3]||"";var head=iconName?'<span class="ic">'+ic(iconName)+"</span>":"";node.innerHTML=head+"<span>"+esc(bt[0])+"</span>";node.addEventListener("click",bt[2]);b.appendChild(node);});showOverlay("menu-overlay");}
function showConfirm(title,msg,onYes,yesLabel){if(typeof msg==="function"){yesLabel=onYes;onYes=msg;msg="Cette action est irréversible.";}var t=$("confirm-title");if(t)t.textContent=title;var b=$("confirm-body");if(b)b.innerHTML='<p style="font-size:15px;line-height:1.6;">'+esc(msg)+"</p>";var f=$("confirm-foot");if(!f)return;f.innerHTML="";var no=el("button","","<span>Annuler</span>");no.addEventListener("click",function(){hideOverlay("confirm-overlay");});var yes=el("button","primary","<span>"+esc(yesLabel||"Confirmer")+"</span>");yes.addEventListener("click",function(){hideOverlay("confirm-overlay");if(onYes)onYes();});f.appendChild(no);f.appendChild(yes);showOverlay("confirm-overlay");}
async function refreshAll(){ST.entries=await dbAll();renderCollection();renderJournal();updateJournalBadge();scheduleGitHubBackup();}
function updateJournalBadge(){var total=0;ST.entries.forEach(function(e){total+=(e.journal||[]).length;});var badge=$("journal-badge");if(!badge)return;if(ST.lastJournalCount===0){badge.style.display="none";ST.lastJournalCount=total;return;}if(total>ST.lastJournalCount&&ST.view!=="journal")badge.style.display="block";else badge.style.display="none";ST.lastJournalCount=total;}

function neonClass(e){if(e.aVoir)return"n-voir";if(e.enCours)return"n-enc";return"n-fini";}
function statIcon(e){if(e.aVoir)return ic("eye");if(e.enCours)return ic("hourglass");return ic("check");}
function fmtWhen(v){if(!v)return nowStamp();var p=parseDateFR(v);if(!p)return nowStamp();return pad2(p.d)+"/"+pad2(p.mo);}
function toInputDate(s){var p=parseDateFR(s);if(!p)return"";return p.y+"-"+pad2(p.mo)+"-"+pad2(p.d);}
function openPosterZoom(url){if(!url)return;var img=$("poster-img");if(img)img.src=url;showOverlay("poster-overlay");}
function openReaderForEntry(entry,idx){ST.currentReaderEntry=entry;ST.currentReaderJournalIdx=idx;var jl=entry.journal||[];var x=jl[idx]||{text:""};var t=$("r-title");if(t)t.textContent=entry.titre;var s=$("r-sub");if(s)s.textContent=entryTag(x);var b=$("r-body");if(b)b.textContent=x.text||"";showOverlay("reader-overlay");}

function renderPoster(e,showProg){
  var p=el("div","poster "+neonClass(e));
  var img=el("img","art");img.src=e.posterThumb||e.posterUrl||NO_POSTER;img.alt="";img.loading="lazy";p.appendChild(img);
  if(e.note!=null){var solid=noteSolid(e.note);if(solid){p.classList.add("has-note");p.style.borderColor=solid;}var pn=el("div","pnote",e.note+"/10");var nc=noteColors(e.note);if(nc){pn.style.background=nc[0];pn.style.color=nc[1];}p.appendChild(pn);}
  if(e.coeur)p.appendChild(el("div","pheart",ic("heart")));
  if(showProg!==false){var pb=progressBadge(e);if(pb)p.appendChild(el("div","pp",esc(pb)));}
  var st=el("div","pstat");st.innerHTML=statIcon(e);p.appendChild(st);
  return p;
}
function syncPoster(e){var host=$("d-poster");if(!host)return;host.classList.remove("n-fini","n-enc","n-voir","has-note");host.classList.add(neonClass(e));var solid=noteSolid(e.note);host.style.borderColor=solid||"";if(solid)host.classList.add("has-note");var pn=host.querySelector(".pnote");if(pn){if(e.note!=null){pn.style.display="";pn.textContent=e.note+"/10";var nc=noteColors(e.note);if(nc){pn.style.background=nc[0];pn.style.color=nc[1];}}else pn.style.display="none";}var ps=host.querySelector(".pstat");if(ps)ps.innerHTML=statIcon(e);var ph=host.querySelector(".pheart");if(ph&&!e.coeur)ph.remove();if(!ph&&e.coeur)host.insertBefore(el("div","pheart",ic("heart")),host.querySelector(".pstat"));var pb=host.querySelector(".pp");var txt=progressBadge(e);if(pb&&!txt)pb.remove();if(!pb&&txt)host.insertBefore(el("div","pp",esc(txt)),host.querySelector(".pstat"));else if(pb)pb.textContent=txt;}

function epNoted(entry,s){var set={};(entry.journal||[]).forEach(function(x){if(x.kind==="ep"&&x.s===s)set[x.e]=1;});return set;}
function nextEpFor(entry){var eps=(entry.journal||[]).filter(function(x){return x.kind==="ep";});if(!eps.length)return{s:1,e:1};var sMax=0;eps.forEach(function(x){if(x.s>sMax)sMax=x.s;});var eMax=0;eps.forEach(function(x){if(x.s===sMax&&x.e>eMax)eMax=x.e;});return{s:sMax,e:eMax+1};}
function hasEp(entry){if(entry.type==="Série")return true;return(entry.journal||[]).some(function(x){return x.kind==="ep";});}
function nextEpButton(entry){var n=nextEpFor(entry);var b=el("button","next-btn");b.innerHTML='<span class="ic">'+ic("check")+"</span><span>S"+pad2(n.s)+"E"+pad2(n.e)+"</span>";b.addEventListener("click",function(){openEpisodeWindow(entry);});return b;}
function seasonsFromJournal(entry){var set={};(entry.journal||[]).forEach(function(x){if(x.kind==="ep")set[x.s]=1;});var arr=Object.keys(set).map(Number).sort(function(a,b){return a-b;});if(!arr.length)arr=[1];return arr;}
async function openEpisodeWindow(entry,preferS,preferE){var body=el("div");var seasonsLocal=seasonsFromJournal(entry);var tmdb=null;if(entry.tmdb_id){try{tmdb=await fetchTMDBSeasons(entry.tmdb_id);}catch(e){tmdb=null;}}var seasons;if(tmdb&&tmdb.length)seasons=tmdb.map(function(s){return{n:s.n,total:s.total};});else seasons=seasonsLocal.map(function(n){var noted=epNoted(entry,n),mx=0;for(var k in noted)if(+k>mx)mx=+k;return{n:n,total:mx+8};});var curS=preferS||seasons[0].n;if(!seasons.filter(function(s){return s.n===curS;}).length)curS=seasons[0].n;var pillRow=el("div","season-row");body.appendChild(pillRow);var head=el("div","ep-head");var stEl=el("span","st",""),cntEl=el("span","cnt","");head.appendChild(stEl);head.appendChild(cntEl);body.appendChild(head);var quick=el("div","quick");function qb(label,iconName,fn){var b=el("button","qbtn");b.innerHTML='<span class="ic">'+ic(iconName)+"</span><span>"+esc(label)+"</span>";b.addEventListener("click",fn);quick.appendChild(b);}qb("Jusqu'au suivant","check",function(){toggleUpTo(entry,curS);rebuild();});qb("Tout cocher","grid",function(){setAll(entry,curS,true);rebuild();});qb("Tout décocher","x",function(){setAll(entry,curS,false);rebuild();});body.appendChild(quick);var grid=el("div","ep-grid");body.appendChild(grid);var info=el("div","status");info.style.textAlign="center";body.appendChild(info);function renderPills(){pillRow.innerHTML="";seasons.forEach(function(s){var p=el("button","season-pill"+(s.n===curS?" on":""),"<span>S"+pad2(s.n)+"</span>");p.addEventListener("click",function(){curS=s.n;rebuild();});pillRow.appendChild(p);});}function rebuild(){renderPills();var sObj=seasons.filter(function(s){return s.n===curS;})[0]||{n:curS,total:8};var noted=epNoted(entry,curS),total=sObj.total,seen=0;for(var k in noted)seen++;stEl.textContent="Saison "+curS;cntEl.textContent=seen+" / "+total+" vus";grid.innerHTML="";for(var e=1;e<=total;e++){(function(e){var isSeen=!!noted[e];var c=el("div","ep-cell"+(isSeen?" seen":""),"<span>"+e+"</span>");if(isSeen)c.insertAdjacentHTML("beforeend",'<svg class="chk" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><polyline points="20 6 9 17 4 12"/></svg>');c.addEventListener("click",function(){toggleEp(entry,curS,e);rebuild();});grid.appendChild(c);})(e);}info.textContent=tmdb?"":"Saison sans total connu : la liste s'étend au besoin.";}rebuild();setSheet("Saisons et épisodes : "+entry.titre,body,[["Fermer","",closeMenu,"x"]]);}
function toggleEp(entry,s,e){if(!entry.journal)entry.journal=[];var idx=-1;for(var i=0;i<entry.journal.length;i++){var x=entry.journal[i];if(x.kind==="ep"&&x.s===s&&x.e===e){idx=i;break;}}if(idx>=0)entry.journal.splice(idx,1);else entry.journal.push({kind:"ep",s:s,e:e,note:null,text:"Vu",at:Date.now()});dbPut(entry).then(refreshAll);}
function setAll(entry,s,on){if(!entry.journal)entry.journal=[];var noted=epNoted(entry,s),mx=0;for(var k in noted)if(+k>mx)mx=+k;var total=Math.max(8,mx+8);if(on){for(var e=1;e<=total;e++)if(!noted[e])entry.journal.push({kind:"ep",s:s,e:e,note:null,text:"Vu",at:Date.now()+e});}else entry.journal=entry.journal.filter(function(x){return!(x.kind==="ep"&&x.s===s);});dbPut(entry).then(refreshAll);}
function toggleUpTo(entry,s){if(!entry.journal)entry.journal=[];var noted=epNoted(entry,s),mx=0;for(var k in noted)if(+k>mx)mx=+k;var target=mx+1;for(var e=1;e<=target;e++)if(!noted[e])entry.journal.push({kind:"ep",s:s,e:e,note:null,text:"Vu",at:Date.now()+e});dbPut(entry).then(refreshAll);}

function collectionCard(e){var cell=el("div","grid-cell");cell.appendChild(renderPoster(e,false));cell.appendChild(el("div","title",esc(e.titre)));var meta=(e.support||"")+(e.packaging?" · "+e.packaging:"");if(meta)cell.appendChild(el("div","meta",esc(meta)));cell.addEventListener("click",function(ev){if(ev.target.closest("button"))return;showCollectionDetail(e);});return cell;}
function detailValueBtn(iconName,label,key,val,onOpen){var b=el("button","adv-btn"+(val?" on":""));b.dataset.k=key;b.innerHTML='<span class="ic">'+ic(iconName)+"</span><span>"+esc(label)+'</span><span class="adv-val">'+esc(val||"")+"</span>";b.addEventListener("click",onOpen);return b;}
function detailStatusLabel(e){var a=[];if(e.inCollection)a.push("Bibliothèque");if(e.enCours)a.push("En cours");if(e.aVoir)a.push("À voir");return a.join(" · ");}
function journalCountLabel(e){var n=(e.journal||[]).length;return n?(n+" entrée"+(n>1?"s":"")):"";}
function showCollectionDetail(e){
  var body=el("div");var head=el("div","detail-head");var pw=el("div","detail-poster");var poster=renderPoster(e,true);poster.id="d-poster";var img=poster.querySelector("img");if(img)img.addEventListener("click",function(){openPosterZoom(img.src);});var zb=el("div","zoom-btn");zb.innerHTML='<span class="ic">'+ic("maximize-2")+"</span><span>Agrandir</span>";zb.addEventListener("click",function(){openPosterZoom(img?img.src:poster.querySelector("img").src);});poster.appendChild(zb);pw.appendChild(poster);head.appendChild(pw);
  var info=el("div");info.style.cssText="flex:1;min-width:0;";var h2=el("h2","",esc(e.titre));h2.style.cssText="font-family:var(--ft);font-size:21px;margin-bottom:10px;";info.appendChild(h2);var tags=el("div","tagline");tags.appendChild(el("span","tag",esc(e.type)));if(e.support)tags.appendChild(el("span","tag",esc(e.support)));info.appendChild(tags);var heartRow=el("div","detail-heart");var heartBtn=makeHeartButton(!!e.coeur,function(on){e.coeur=on;heartBtn.id="d-heart";dbPut(e).then(function(){toast(on?"Coup de cœur":"Coup de cœur retiré");syncPoster(e);refreshAll();});});heartBtn.id="d-heart";heartRow.appendChild(heartBtn);info.appendChild(heartRow);if(hasEp(e))info.appendChild(nextEpButton(e));head.appendChild(info);body.appendChild(head);
  var save=function(patch,label){patch(e);dbPut(e).then(function(){toast(label);syncPoster(e);refreshAll();});};
  var grid=el("div","adv-grid");
  grid.appendChild(detailValueBtn("star","Note","note",e.note!=null?e.note+"/10":"",function(){openNoteSheet(e.note,!!e.coeur,function(n,c){updateAdvBtn("note",n!=null?n+"/10":"");save(function(x){x.note=n;x.coeur=c;},"Note enregistrée");var hb=$("d-heart");if(hb){hb.classList.toggle("on",!!c);}});}));
  grid.appendChild(detailValueBtn("flag","Statuts","statuts",detailStatusLabel(e),function(){openStatusSheet({isInCollection:!!e.inCollection,isEnc:!!e.enCours,isVoir:!!e.aVoir},function(st){updateAdvBtn("statuts",st.isInCollection?(st.isEnc?"Bibliothèque · En cours":st.isVoir?"Bibliothèque · À voir":"Bibliothèque"):(st.isEnc?"En cours":st.isVoir?"À voir":""));save(function(x){x.inCollection=st.isInCollection;x.enCours=st.isEnc;x.aVoir=st.isVoir;},"Statuts mis à jour");});}));
  grid.appendChild(detailValueBtn("notebook-pen","Journal","journal",journalCountLabel(e),function(){openJournalSheet({kind:"entry",e:e},function(){updateAdvBtn("journal",journalCountLabel(e));syncPoster(e);});}));
  grid.appendChild(detailValueBtn("calendar-check","Date de fin","dateFin",e.dateFin?formatDate(e.dateFin):"",function(){openDatePicker(e.dateFin,function(iso){updateAdvBtn("dateFin",iso?formatDate(iso):"");save(function(x){x.dateFin=iso?formatDate(iso):"";},"Date de fin enregistrée");});}));
  grid.appendChild(detailValueBtn("shopping-cart","Date d'achat","dateAchat",e.dateAchat?formatDate(e.dateAchat):"",function(){openDatePicker(e.dateAchat,function(iso){updateAdvBtn("dateAchat",iso?formatDate(iso):"");save(function(x){x.dateAchat=iso||"";x.inCollection=true;},"Date d'achat enregistrée");});}));
  grid.appendChild(detailValueBtn("monitor","Plateforme","plateforme",e.plateforme||"",function(){openListSheet("plateformes",e.plateforme,function(v){updateAdvBtn("plateforme",v);save(function(x){x.plateforme=v;x.inCollection=true;},"Plateforme : "+v);});}));
  grid.appendChild(detailValueBtn("box","Support","support",e.support||"",function(){openListSheet("supports",e.support,function(v){updateAdvBtn("support",v);save(function(x){x.support=v;x.inCollection=true;},"Support : "+v);});}));
  grid.appendChild(detailValueBtn("package-open","Packaging","packaging",e.packaging||"",function(){openListSheet("packagings",e.packaging,function(v){updateAdvBtn("packaging",v);save(function(x){x.packaging=v;x.inCollection=true;},"Packaging : "+v);});}));
  grid.appendChild(detailValueBtn("gift","Bonus","bonus",(e.bonus||[]).join(", "),function(){openBonusSheet(e.bonus||[],function(arr){updateAdvBtn("bonus",arr.join(", "));save(function(x){x.bonus=arr;x.inCollection=true;},"Bonus mis à jour");});}));
  grid.appendChild(detailValueBtn("hash","Édition","edition",e.edition||"",function(){openEditionSheet(e.edition||"",function(v){updateAdvBtn("edition",v);save(function(x){x.edition=v;x.inCollection=true;},"Édition enregistrée");});}));
  grid.appendChild(detailValueBtn("barcode","EAN","ean",e.ean||"",function(){openEanSheet(e.ean||"",function(v){updateAdvBtn("ean",v);save(function(x){x.ean=v;},"EAN enregistré");});}));
  grid.appendChild(detailValueBtn("link","URL","url",e.url?"Lien":"",function(){openUrlSheet(e.url||"",function(v){updateAdvBtn("url",v?"Lien":"");save(function(x){x.url=v;},"URL enregistrée");});}));
  body.appendChild(fieldBox("Bibliothèque",grid));
  if(e.url){var ob=btn("Ouvrir la fiche","link","wide",function(){window.open(e.url,"_blank");});ob.style.marginBottom="16px";body.appendChild(ob);}
  var acts=el("div","detail-actions");acts.appendChild(btn("Noter vite","plus","",function(){quickNoteOpen(e,"","time",null,{kind:"entry",e:e});}));acts.appendChild(btn("Dupliquer","duplicate","",function(){duplicateEntry(e);}));acts.appendChild(btn("Journal","notebook-pen","",function(){openJournalSheet({kind:"entry",e:e},function(){updateAdvBtn("journal",journalCountLabel(e));syncPoster(e);});}));body.appendChild(acts);
  setModal(e.titre,body,[["Modifier","primary",function(){renderPanel(e);},"pen"],["Supprimer","",function(){showConfirm("Supprimer "+e.titre+" ?","Toutes les entrées de journal seront perdues.",function(){dbDelete(e.id).then(function(){toast("Supprimé");closeModal();refreshAll();});},"trash-2");},"trash-2"]]);
}

function capturePanel(){var t=$("p-title");if(t)ST.draft.titre=t.value;var c=$("p-comment");if(c)ST.draft.comment=c.value;var s=$("p-sub");if(s)ST.draft.sub=s.value;}
function rerenderPanel(){capturePanel();renderPanel(ST.editing,true);}
function updateAdvBtn(key,val){var b=document.querySelector('#m-body .adv-btn[data-k="'+key+'"]');if(!b)return;var v=b.querySelector(".adv-val");if(v)v.textContent=val||"";b.classList.toggle("on",!!val);}
function markCollection(){ST.isInCollection=true;}
function formStatusLabel(){var a=[];if(ST.isInCollection)a.push("Bibliothèque");if(ST.isEnc)a.push("En cours");if(ST.isVoir)a.push("À voir");return a.join(" · ");}
function renderPanel(entry,keepDraft){
  ST.editing=entry||null;
  if(!keepDraft){
    if(entry){ST.panelType=entry.type;ST.currentNote=entry.note!=null?entry.note:null;ST.isCoeur=!!entry.coeur;ST.isEnc=!!entry.enCours;ST.isVoir=!!entry.aVoir;ST.isInCollection=!!entry.inCollection;ST.panelPoster=entry.posterUrl||"";ST.panelThumb=entry.posterThumb||"";ST.advFields={plateforme:entry.plateforme||"",dateAchat:entry.dateAchat||"",edition:entry.edition||"",bonus:(entry.bonus||[]).slice(),support:entry.support||"",packaging:entry.packaging||"",ean:entry.ean||"",url:entry.url||""};ST.draft={titre:entry.titre||"",date:toInputDate(entry.dateFin||""),comment:entry.comment||"",sub:entry.sousTitre||""};ST.draftJournal=JSON.parse(JSON.stringify(entry.journal||[]));}
    else{ST.panelType=ST.currentType;ST.currentNote=null;ST.isCoeur=false;ST.isEnc=false;ST.isVoir=false;ST.isInCollection=false;ST.panelPoster=(ST.selectedItem&&ST.selectedItem.poster)||"";ST.panelThumb="";ST.advFields={plateforme:"",dateAchat:"",edition:"",bonus:[],support:"",packaging:"",ean:"",url:""};ST.draft={titre:(ST.selectedItem&&ST.selectedItem.title)||"",date:todayFR(),comment:"",sub:""};ST.draftJournal=[];}
  }
  var s=settingsLoad();s.panelMode="simple";settingsSave(s);var mode="simple";var body=el("div");var seg=el("div","seg");var formHost=el("div");formHost.id="p-form";
  [["simple","Simple"],["avance","Avancé"]].forEach(function(m){var b=el("button",mode===m[0]?"on":"","<span>"+m[1]+"</span>");b.addEventListener("click",function(){capturePanel();mode=m[0];seg.querySelectorAll("button").forEach(function(x){x.classList.remove("on");});b.classList.add("on");buildForm(formHost,mode);});seg.appendChild(b);});
  body.appendChild(seg);body.appendChild(formHost);buildForm(formHost,mode);
  setModal(entry?"Modifier l'œuvre":"Nouvelle œuvre",body,[["Enregistrer","primary",saveCurrentEntry,"save"],["Annuler","",closeModal,"x"]]);
}
function buildForm(host,mode){
  host.innerHTML="";
  var tIn=el("input");tIn.id="p-title";tIn.value=ST.draft.titre;tIn.placeholder="Titre de l'œuvre";host.appendChild(fieldBox("Titre",tIn));
  host.appendChild(fieldBox("Note",detailValueBtn("star","Note","note",ST.currentNote!=null?ST.currentNote+"/10":"",function(){openNoteSheet(ST.currentNote,ST.isCoeur,function(n,c){ST.currentNote=n;ST.isCoeur=c;updateAdvBtn("note",n!=null?n+"/10":"");});})));
  host.appendChild(fieldBox("Statuts",detailValueBtn("flag","Statuts","statuts",formStatusLabel(),function(){openStatusSheet({isInCollection:ST.isInCollection,isEnc:ST.isEnc,isVoir:ST.isVoir},function(st){ST.isInCollection=st.isInCollection;ST.isEnc=st.isEnc;ST.isVoir=st.isVoir;updateAdvBtn("statuts",formStatusLabel());});})));
  var cIn=el("textarea");cIn.id="p-comment";cIn.value=ST.draft.comment;cIn.placeholder="Ton avis…";host.appendChild(fieldBox("Commentaire",cIn));
  host.appendChild(fieldBox("Journal",detailValueBtn("notebook-pen","Journal","journal",ST.draftJournal.length?(ST.draftJournal.length+" entrée"+(ST.draftJournal.length>1?"s":"")):"",function(){openJournalSheet({kind:"draft"},function(){updateAdvBtn("journal",ST.draftJournal.length?(ST.draftJournal.length+" entrée"+(ST.draftJournal.length>1?"s":"")):"");});})));
  host.appendChild(fieldBox("Date de fin / lecture",detailValueBtn("calendar-check","Date","dateFin",ST.draft.date?formatDate(ST.draft.date):"",function(){openDatePicker(ST.draft.date,function(iso){ST.draft.date=iso||"";updateAdvBtn("dateFin",iso?formatDate(iso):"");});})));
  var ar=el("div","poster-row");var prev=el("img");prev.id="p-prev";prev.src=ST.panelPoster||NO_POSTER;prev.addEventListener("click",function(){openPosterZoom(prev.src);});var pbtns=el("div","poster-btns");var bU=el("button","poster-btn");bU.innerHTML='<span class="ic">'+ic("link")+"</span><span>URL</span>";bU.addEventListener("click",function(){var b2=el("div");var inp=el("input");inp.placeholder="https://…";inp.value=ST.panelPoster||"";b2.appendChild(inp);setSheet("URL de l'affiche",b2,[["Valider","primary",function(){var v=inp.value.trim();if(v){ST.panelPoster=v;prev.src=v;makeThumb(v).then(function(t){ST.panelThumb=t;});}closeMenu();},"check"],["Annuler","",closeMenu,"x"]]);});var bI=el("button","poster-btn");bI.innerHTML='<span class="ic">'+ic("folder")+"</span><span>Importer</span>";var fI=el("input");fI.type="file";fI.accept="image/*";fI.hidden=true;bI.addEventListener("click",function(){fI.click();});fI.addEventListener("change",function(ev){var f=ev.target.files[0];if(f)fileToResized(f,500).then(function(u){ST.panelPoster=u;prev.src=u;makeThumb(u).then(function(t){ST.panelThumb=t;});});});pbtns.appendChild(bU);pbtns.appendChild(bI);pbtns.appendChild(fI);ar.appendChild(prev);ar.appendChild(pbtns);host.appendChild(fieldBox("Affiche",ar));
  if(mode==="avance"){
    var sIn=el("input");sIn.id="p-sub";sIn.value=ST.draft.sub;sIn.placeholder="Sous-titre, détail…";host.appendChild(fieldBox("Détail / sous-titre",sIn));
    var cg=el("div","adv-grid");
    cg.appendChild(detailValueBtn("shopping-cart","Date d'achat","dateAchat",ST.advFields.dateAchat?formatDate(ST.advFields.dateAchat):"",function(){openDatePicker(ST.advFields.dateAchat,function(iso){ST.advFields.dateAchat=iso||"";if(iso)markCollection();updateAdvBtn("dateAchat",iso?formatDate(iso):"");});}));
    cg.appendChild(detailValueBtn("monitor","Plateforme","plateforme",ST.advFields.plateforme,function(){openListSheet("plateformes",ST.advFields.plateforme,function(v){ST.advFields.plateforme=v;markCollection();updateAdvBtn("plateforme",v);});}));
    cg.appendChild(detailValueBtn("box","Support","support",ST.advFields.support,function(){openListSheet("supports",ST.advFields.support,function(v){ST.advFields.support=v;markCollection();updateAdvBtn("support",v);});}));
    cg.appendChild(detailValueBtn("package-open","Packaging","packaging",ST.advFields.packaging,function(){openListSheet("packagings",ST.advFields.packaging,function(v){ST.advFields.packaging=v;markCollection();updateAdvBtn("packaging",v);});}));
    cg.appendChild(detailValueBtn("gift","Bonus","bonus",ST.advFields.bonus.join(", "),function(){openBonusSheet(ST.advFields.bonus,function(arr){ST.advFields.bonus=arr;if(arr.length)markCollection();updateAdvBtn("bonus",arr.join(", "));});}));
    cg.appendChild(detailValueBtn("hash","Édition","edition",ST.advFields.edition,function(){openEditionSheet(ST.advFields.edition,function(v){ST.advFields.edition=v;if(v)markCollection();updateAdvBtn("edition",v);});}));
    cg.appendChild(detailValueBtn("barcode","EAN","ean",ST.advFields.ean,function(){openEanSheet(ST.advFields.ean,function(v){ST.advFields.ean=v;if(v)markCollection();updateAdvBtn("ean",v);});}));
    cg.appendChild(detailValueBtn("link","URL fiche","url",ST.advFields.url?"Lien":"",function(){openUrlSheet(ST.advFields.url,function(v){ST.advFields.url=v;if(v)markCollection();updateAdvBtn("url",v?"Lien":"");});}));
    host.appendChild(fieldBox("Détails bibliothèque",cg));
    var sl=el("div","search-links");sl.appendChild(el("span","","Chercher ailleurs :"));var q=encodeURIComponent(ST.draft.titre||"");[{name:"Google",icon:"search",url:"https://www.google.com/search?q="+q},{name:"Steam",icon:"gamepad-2",url:"https://store.steampowered.com/search/?term="+q},{name:"TMDB",icon:"film",url:"https://www.themoviedb.org/search?query="+q},{name:"SensCritique",icon:"heart",url:"https://www.senscritique.com/recherche?query="+q}].forEach(function(l){var a=el("a","search-link");a.href=l.url;a.target="_blank";a.innerHTML='<span class="ic">'+ic(l.icon)+"</span><span>"+l.name+"</span>";sl.appendChild(a);});host.appendChild(fieldBox("Recherche externe",sl));
  }
}
function choiceRow(item,selected,onPick,onDelete){var row=el("div","radio-opt"+(selected?" sel":""));row.innerHTML='<span class="dot"></span>'+valueIconHTML(item)+'<span class="lbl">'+esc(item.name)+"</span>";var lbl=row.querySelector(".lbl");if(lbl){lbl.style.flex="1";lbl.style.minWidth="0";lbl.style.overflow="hidden";lbl.style.textOverflow="ellipsis";lbl.style.whiteSpace="nowrap";}row.addEventListener("click",onPick);if(onDelete){var del=el("button","sq-btn ml-del");del.setAttribute("aria-label","Supprimer ce choix");del.innerHTML='<span class="ic">'+ic("trash")+"</span>";del.addEventListener("click",function(ev){ev.stopPropagation();onDelete();});row.appendChild(del);}return row;}
function freeRow(onFree){var b=el("button","wide");b.style.cssText="justify-content:flex-start;margin-top:10px;";b.innerHTML='<span class="ic">'+ic("more-horizontal")+'</span><span style="font-style:italic;">Autre… (libre)</span>';b.addEventListener("click",onFree);return b;}
function openListSheet(listKey,current,onPick){var wrap=el("div","radio-list");function rebuild(){wrap.innerHTML="";listItems(listKey).forEach(function(it){wrap.appendChild(choiceRow(it,current===it.name,function(){onPick(it.name);closeMenu();},it.base?null:function(){removeCustom(listKey,it.name);rebuild();}));});wrap.appendChild(freeRow(function(){var b2=el("div");var i=el("input");i.placeholder="Ta valeur libre…";b2.appendChild(i);setSheet("Valeur libre",b2,[["Valider","primary",function(){var v=i.value.trim();if(!v)return;addCustom(listKey,v);onPick(v);closeMenu();},"check"],["Annuler","",rebuild,"x"]]));});}rebuild();setSheet("Choix",wrap,[["Annuler","",closeMenu,"x"]]);}
function openBonusSheet(currentArr,onPick){var arr=(currentArr||[]).slice();var wrap=el("div","radio-list");function rebuild(){wrap.innerHTML="";listItems("bonus").forEach(function(it){var on=arr.indexOf(it.name)>=0;wrap.appendChild(choiceRow(it,on,function(){var i=arr.indexOf(it.name);if(i>=0)arr.splice(i,1);else arr.push(it.name);rebuild();},it.base?null:function(){removeCustom("bonus",it.name);var ix=arr.indexOf(it.name);if(ix>=0)arr.splice(ix,1);rebuild();}));});wrap.appendChild(freeRow(function(){var b2=el("div");var i=el("input");i.placeholder="Ton bonus…";b2.appendChild(i);setSheet("Bonus libre",b2,[["Valider","primary",function(){var v=i.value.trim();if(!v)return;addCustom("bonus",v);if(arr.indexOf(v)<0)arr.push(v);closeMenu();rebuild();},"check"],["Annuler","",rebuild,"x"]]));});}rebuild();setSheet("Bonus",wrap,[["Valider","primary",function(){onPick(arr);closeMenu();},"check"],["Annuler","",closeMenu,"x"]]);}
function openEditionSheet(current,onPick){var b=el("div");var i=el("input");i.placeholder="Édition limitée…";i.value=current||"";b.appendChild(i);setSheet("Édition",b,[["Valider","primary",function(){onPick(i.value.trim());closeMenu();},"check"],["Annuler","",closeMenu,"x"]]);}
function openEanSheet(current,onPick){var b=el("div");var i=el("input");i.placeholder="Code EAN";i.inputMode="numeric";i.value=current||"";b.appendChild(i);var sc=btn("Scanner le code-barres","camera","wide",function(){startEAN(function(code){onPick(code);closeMenu();});});sc.style.marginTop="12px";b.appendChild(sc);setSheet("EAN",b,[["Valider","primary",function(){onPick(i.value.trim());closeMenu();},"check"],["Annuler","",closeMenu,"x"]]);}
function openUrlSheet(current,onPick){var b=el("div");var i=el("input");i.placeholder="URL de la fiche";i.value=current||"";b.appendChild(i);setSheet("URL",b,[["Valider","primary",function(){onPick(i.value.trim());closeMenu();},"check"],["Annuler","",closeMenu,"x"]]);}
function openNoteSheet(current,coeur,cb){var selected=current;var isCoeur=!!coeur;var b=el("div");var ng=el("div","note-grid");function paint(){ng.querySelectorAll(".note-btn").forEach(function(x){var n=+x.dataset.n;var c=noteColors(n);x.style.background=c?c[0]:"";x.style.color=c?c[1]:"";x.style.borderColor=n===selected?"transparent":"";x.classList.toggle("sel",n===selected);});}for(var n=1;n<=10;n++){(function(n){var c=el("button","note-btn","<span>"+n+"</span>");c.dataset.n=n;c.addEventListener("click",function(){selected=n;paint();});ng.appendChild(c);})(n);}b.appendChild(ng);paint();var hr=el("div","heart-row");hr.appendChild(makeHeartButton(isCoeur,function(on){isCoeur=on;}));b.appendChild(hr);if(selected!=null){var rb=btn("Retirer la note","x","wide",function(){selected=null;paint();});rb.style.marginTop="14px";b.appendChild(rb);}setSheet("Note /10",b,[["Valider","primary",function(){cb(selected,isCoeur);closeMenu();},"check"],["Annuler","",closeMenu,"x"]]);}
function openStatusSheet(state,onPick){var st={isInCollection:!!state.isInCollection,isEnc:!!state.isEnc,isVoir:!!state.isVoir};var b=el("div","chips");function mk(key,label,iconName){var c=el("div","chip"+(st[key]?" on":""),'<span class="ic">'+ic(iconName)+"</span><span>"+label+"</span>");c.addEventListener("click",function(){st[key]=!st[key];c.classList.toggle("on",st[key]);});b.appendChild(c);}mk("isInCollection","Ajouter à ma bibliothèque","box");mk("isEnc","En cours","hourglass");mk("isVoir","À voir","eye");setSheet("Statuts",b,[["Valider","primary",function(){onPick(st);closeMenu();},"check"],["Annuler","",closeMenu,"x"]]);}
function getJournalArr(dest){return dest.kind==="draft"?ST.draftJournal:(dest.e.journal||(dest.e.journal=[]));}
function openJournalSheet(dest,afterChange){var body=el("div");var list=el("div");body.appendChild(list);var addBtn=btn("Ajouter une entrée","plus","wide",function(){quickNoteOpen(dest.kind==="entry"?dest.e:null,"","time",null,dest);});addBtn.style.marginTop="16px";body.appendChild(addBtn);function rebuild(){list.innerHTML="";var arr=getJournalArr(dest);if(!arr.length){list.appendChild(emptyBox("notebook-pen","Aucune entrée."));return;}arr.forEach(function(x,i){var row=el("div","jrow");var txt=el("div","jb");txt.style.cursor="pointer";txt.innerHTML='<div class="jt">'+esc(entryTag(x))+'</div><div class="jx">'+esc(x.text||"")+"</div>";if(dest.kind==="entry")txt.addEventListener("click",function(){closeMenu();openReaderForEntry(dest.e,i);});var ed=el("button");ed.setAttribute("aria-label","Modifier");ed.innerHTML='<span class="ic">'+ic("pen")+"</span>";ed.addEventListener("click",function(){quickNoteOpen(dest.kind==="entry"?dest.e:null,x.text,x.kind,i,dest);});var dl=el("button");dl.setAttribute("aria-label","Supprimer");dl.innerHTML='<span class="ic">'+ic("trash-2")+"</span>";dl.addEventListener("click",function(){showConfirm("Supprimer cette entrée ?","",function(){arr.splice(i,1);if(dest.kind==="entry")dbPut(dest.e).then(function(){toast("Supprimée");rebuild();refreshAll();if(afterChange)afterChange();});else{rebuild();if(afterChange)afterChange();}},"trash-2");});row.appendChild(txt);row.appendChild(ed);row.appendChild(dl);list.appendChild(row);});}rebuild();setSheet(dest.kind==="draft"?"Journal (brouillon)":"Journal : "+dest.e.titre,body,[["Fermer","",closeMenu,"x"]]);ST.journalSheetRebuild=rebuild;}
function saveCurrentEntry(){capturePanel();var title=ST.draft.titre.trim();if(!title){toast("Titre obligatoire.");return;}if(ST.editing){finishSave(ST.editing,ST.editing.id,ST.editing.dateAjout);return;}var type=ST.panelType,dup=null;for(var i=0;i<ST.entries.length;i++){if(ST.entries[i].type===type&&norm(ST.entries[i].titre)===norm(title)){dup=ST.entries[i];break;}}if(dup)showConfirm("Doublon détecté",dup.titre+" existe déjà. Modifier l'existant ?",function(){finishSave(dup,dup.id,dup.dateAjout);},"Modifier");else finishSave(null,null,null);}
async function finishSave(base,entryId,dateAjout){var type=ST.panelType;base=base||{};if(!entryId){var sid=(ST.selectedItem&&ST.selectedItem.id)||Date.now();entryId=type+"_"+sid;var exists=false;for(var k=0;k<ST.entries.length;k++){if(ST.entries[k].id===entryId){exists=true;break;}}if(exists)entryId=entryId+"_"+Date.now();dateAjout=new Date().toISOString();}var e=Object.assign({},base);e.id=entryId;e.type=type;e.titre=ST.draft.titre.trim();e.sousTitre=(ST.draft.sub||"").trim();e.note=ST.currentNote;e.coeur=ST.isCoeur;e.enCours=ST.isEnc;e.aVoir=ST.isVoir;e.inCollection=ST.isInCollection;e.dateFin=ST.draft.date?formatDate(ST.draft.date):"";e.comment=ST.draft.comment.trim();e.journal=ST.draftJournal;e.posterUrl=ST.panelPoster;e.posterThumb=ST.panelThumb||(await makeThumb(ST.panelPoster));if(ST.selectedItem&&ST.selectedItem.source==="tmdb"&&ST.selectedItem.tmdbId)e.tmdb_id=ST.selectedItem.tmdbId;if(ST.isInCollection){e.plateforme=ST.advFields.plateforme||null;e.dateAchat=ST.advFields.dateAchat||null;e.edition=ST.advFields.edition||null;e.bonus=ST.advFields.bonus.slice();e.support=ST.advFields.support||null;e.packaging=ST.advFields.packaging||null;e.ean=ST.advFields.ean||"";e.url=ST.advFields.url||"";}else{e.plateforme=null;e.dateAchat=null;e.edition=null;e.bonus=[];e.support=null;e.packaging=null;e.ean="";e.url="";}e.dateAjout=dateAjout;await dbPut(e);if(navigator.vibrate)navigator.vibrate(25);toast("Enregistré");closeModal();refreshAll();}
function duplicateEntry(e){ST.selectedItem=null;ST.editing=null;closeModal();setTimeout(function(){renderPanel(null);ST.draftJournal=[];ST.draft.titre=e.titre;ST.panelType=e.type;},60);}
function quickNoteOpen(e,preText,kind,idx,dest){ST.qnEntry=e||null;ST.qnEditIdx=(idx!=null?idx:null);ST.qnKind=kind||"time";ST.qnDest=dest||(e?{kind:"entry",e:e}:{kind:"global"});ST.pickerVal=null;var t=$("qn-title");if(t)t.textContent=(ST.qnEditIdx!=null?"Modifier : ":"Noter : ")+(e?e.titre:"note libre");var txt=$("qn-text");if(txt)txt.value=preText||"";var lbl=$("qn-entry-label");if(lbl)lbl.textContent=e?e.titre:"Choisir une œuvre…";var erow=$("qn-entry-row");if(erow)erow.classList.toggle("hidden",!!e);syncQnKind();var sb=$("qn-save");if(sb)sb.innerHTML=ST.qnEditIdx!=null?'<span class="ic">'+ic("save")+"</span><span>Remplacer</span>":'<span class="ic">'+ic("plus")+"</span><span>Ajouter</span>";var k=$("qn-kind");if(!k)return;k.innerHTML="";KINDS.forEach(function(x){var c=el("div","chip"+(x[0]===ST.qnKind?" on":""),'<span class="ic">'+ic(x[2])+"</span><span>"+x[1]+"</span>");c.addEventListener("click",function(){ST.qnKind=x[0];k.querySelectorAll(".chip").forEach(function(y){y.classList.remove("on");});c.classList.add("on");syncQnKind();});k.appendChild(c);});showOverlay("qn-overlay");}
function syncQnKind(){var w=$("qn-when-row");if(w)w.classList.toggle("hidden",ST.qnKind!=="time");var e=$("qn-ep-row");if(e)e.classList.toggle("hidden",ST.qnKind!=="ep");var p=$("qn-pages-row");if(p)p.classList.toggle("hidden",ST.qnKind!=="pages");var s=$("qn-session-row");if(s)s.classList.toggle("hidden",ST.qnKind!=="session");if(ST.qnKind==="time"){var wl=$("qn-when-label");if(wl)wl.textContent=ST.pickerVal?fmtWhen(ST.pickerVal):nowStamp();}}
function quickNoteClose(){hideOverlay("qn-overlay");ST.qnEditIdx=null;}
async function quickNoteSave(){var txt=$("qn-text");var text=txt?txt.value.trim():"";if(!text&&ST.qnKind!=="ep"&&ST.qnKind!=="pages"){toast("Entre un texte.");return;}var obj=buildQnObj(text);var dest=ST.qnDest||{kind:"global"};if(dest.kind==="draft"){if(ST.qnEditIdx!=null&&ST.draftJournal[ST.qnEditIdx]){obj.at=ST.draftJournal[ST.qnEditIdx].at||obj.at;ST.draftJournal[ST.qnEditIdx]=obj;}else ST.draftJournal.push(obj);toast(ST.qnEditIdx!=null?"Entrée modifiée":"Entrée ajoutée");quickNoteClose();if(ST.journalSheetRebuild)ST.journalSheetRebuild();return;}var e=dest.kind==="entry"?dest.e:ST.qnEntry;if(!e){var fake={id:"libre_"+Date.now(),titre:"Note libre",type:"Livre",journal:[obj],dateFin:todayFR(),dateAjout:new Date().toISOString(),inCollection:false};await dbPut(fake);toast("Note libre ajoutée");quickNoteClose();refreshAll();return;}if(!e.journal)e.journal=[];if(ST.qnEditIdx!=null&&e.journal[ST.qnEditIdx]){obj.at=e.journal[ST.qnEditIdx].at||obj.at;e.journal[ST.qnEditIdx]=obj;}else e.journal.push(obj);await dbPut(e);if(navigator.vibrate)navigator.vibrate(15);toast(ST.qnEditIdx!=null?"Entrée modifiée":"Entrée ajoutée");quickNoteClose();if(ST.journalSheetRebuild&&dest.kind==="entry")ST.journalSheetRebuild();refreshAll();}
function buildQnObj(text){if(ST.qnKind==="time")return{kind:"time",ts:ST.pickerVal?fmtWhen(ST.pickerVal):nowStamp(),text:text,at:ST.pickerVal?isoToAtLocal(ST.pickerVal):Date.now()};if(ST.qnKind==="free")return{kind:"free",ts:nowStamp(),text:text,at:Date.now()};if(ST.qnKind==="session"){var dd=$("qn-dur");return{kind:"session",dur:dd?dd.value.trim():"",text:text,at:Date.now()};}if(ST.qnKind==="pages"){var rd=$("qn-read"),tt=$("qn-total");return{kind:"pages",read:rd?rd.value:"",total:tt?tt.value:"",text:text,at:Date.now()};}var ss=$("qn-s"),ee=$("qn-e");return{kind:"ep",s:parseInt(ss?ss.value||"0":"0",10),e:parseInt(ee?ee.value||"0":"0",10),note:null,text:text,at:Date.now()};}
function openEntryPicker(cb){var wrap=el("div","radio-list");var chosen=null;var free=el("div","radio-opt sel");free.innerHTML='<span class="dot"></span><span class="lbl">Note libre (sans œuvre)</span>';free.addEventListener("click",function(){chosen=null;wrap.querySelectorAll(".radio-opt").forEach(function(x){x.classList.remove("sel");});free.classList.add("sel");});wrap.appendChild(free);ST.entries.forEach(function(en){var o=el("div","radio-opt");o.innerHTML='<span class="dot"></span><span class="lbl">'+esc(en.titre)+"</span>";o.addEventListener("click",function(){chosen=en;wrap.querySelectorAll(".radio-opt").forEach(function(x){x.classList.remove("sel");});o.classList.add("sel");});wrap.appendChild(o);});setSheet("Choisir une œuvre",wrap,[["Valider","primary",function(){closeMenu();cb(chosen);},"check"],["Annuler","",function(){closeMenu();cb(undefined);},"x"]]);}

function entriesByDay(){var set={};ST.entries.forEach(function(en){(en.journal||[]).forEach(function(x){if(!x.at)return;var t=new Date(x.at);set[t.getFullYear()+"-"+pad2(t.getMonth()+1)+"-"+pad2(t.getDate())]=1;});});return set;}
function openDatePicker(initialIso,cb){ST.calMode="pick";ST.calPickCb=cb;var p=parseDateFR(initialIso);var now=new Date();ST.calSel=p?{y:p.y,mo:p.mo-1,d:p.d}:{y:now.getFullYear(),mo:now.getMonth(),d:now.getDate()};ST.calDate=new Date(ST.calSel.y,ST.calSel.mo,ST.calSel.d,12);showOverlay("calendar-overlay");renderCalendar();}
function openJournalCalendar(){ST.calMode="journal";if(!ST.calSel){var now=new Date();ST.calSel={y:now.getFullYear(),mo:now.getMonth(),d:now.getDate()};}ST.calDate=new Date(ST.calSel.y,ST.calSel.mo,ST.calSel.d,12);showOverlay("calendar-overlay");renderCalendar();}
function setCalendarMonthYear(y,mo){var days=new Date(y,mo+1,0).getDate();var d=Math.min(ST.calSel?ST.calSel.d:1,days);ST.calSel={y:y,mo:mo,d:d};ST.calDate=new Date(y,mo,d,12);renderCalendar();}
function renderCalendar(){var cal=$("cal-grid");if(!cal)return;cal.innerHTML="";var dow=$("cal-dow");if(dow){dow.innerHTML="";["L","M","M","J","V","S","D"].forEach(function(d){dow.appendChild(el("span","","<span>"+d+"</span>"));});}var y=ST.calDate.getFullYear(),mo=ST.calDate.getMonth();var mb=$("cal-month-btn"),yb=$("cal-year-btn");if(mb)mb.textContent=MONTHS[mo];if(yb)yb.textContent=y;var first=(new Date(y,mo,1).getDay()+6)%7;var days=new Date(y,mo+1,0).getDate();var today=new Date();var has=ST.calMode==="journal"?entriesByDay():{};for(var i=0;i<first;i++)cal.appendChild(el("div","cal-day empty"));for(var d=1;d<=days;d++){(function(d){var key=y+"-"+pad2(mo+1)+"-"+pad2(d);var noted=!!has[key];var cls="cal-day";if(ST.calMode==="journal"&&!noted)cls+=" muted";if(d===today.getDate()&&mo===today.getMonth()&&y===today.getFullYear())cls+=" today";if(ST.calSel&&ST.calSel.y===y&&ST.calSel.mo===mo&&ST.calSel.d===d)cls+=" sel";var c=el("div",cls,"<span>"+d+"</span>");if(ST.calMode==="journal"&&noted)c.classList.add("has-entry");c.addEventListener("click",function(){if(ST.calMode==="pick"){hideOverlay("calendar-overlay");if(ST.calPickCb)ST.calPickCb(y+"-"+pad2(mo+1)+"-"+pad2(d));ST.calPickCb=null;}else{ST.calSel={y:y,mo:mo,d:d};ST.calDate=new Date(y,mo,d,12);hideOverlay("calendar-overlay");renderJournal();}});cal.appendChild(c);})(d);}var totalCells=first+days;var trail=(7-(totalCells%7))%7;for(var t=0;t<trail;t++)cal.appendChild(el("div","cal-day empty"));}
function openMonthPicker(){var y=ST.calDate.getFullYear();var body=el("div","month-grid");MONTHS.forEach(function(m,i){var b=el("button","cal-pick-btn","<span>"+m+"</span>");b.addEventListener("click",function(){setCalendarMonthYear(y,i);closeMenu();});body.appendChild(b);});setSheet("Mois",body,[["Retour","",closeMenu,"x"]]);}
function openYearPicker(){var current=ST.calDate.getFullYear();var group=Math.floor(current/16)*16;var body=el("div");function render(){body.innerHTML="";var nav=el("div","year-nav");var left=el("button","rnd-btn");left.setAttribute("aria-label","Années précédentes");left.innerHTML=ic("chevron-left");left.disabled=group<=1900;left.addEventListener("click",function(){group-=16;render();});var right=el("button","rnd-btn");right.setAttribute("aria-label","Années suivantes");right.innerHTML=ic("chevron-right");right.disabled=group>=2100;right.addEventListener("click",function(){group+=16;render();});nav.appendChild(left);nav.appendChild(right);body.appendChild(nav);var grid=el("div","year-grid");for(var i=0;i<16;i++){(function(yr){var b=el("button","cal-pick-btn"+(yr===current?" on":""),"<span>"+yr+"</span>");if(yr<1900||yr>2100)b.disabled=true;b.addEventListener("click",function(){setCalendarMonthYear(yr,ST.calDate.getMonth());closeMenu();});grid.appendChild(b);})(group+i);}body.appendChild(grid);}render();setSheet("Année",body,[["Retour","",closeMenu,"x"]]);}

function renderEncours(){var row=$("j-encours");if(!row)return;row.innerHTML="";var enc=ST.entries.filter(function(e){return e.enCours;});if(!enc.length){row.style.display="none";return;}row.style.display="";enc.forEach(function(e){var m=el("div","mini");m.appendChild(renderPoster(e,false));m.appendChild(el("div","t",esc(e.titre)));var l=journalLines(e);m.appendChild(el("div","s",esc(truncate(l.length?l[l.length-1]:"En cours…",30))));m.addEventListener("click",function(){showCollectionDetail(e);});row.appendChild(m);});}
function renderJournal(){if(!ST.calSel){var now=new Date();ST.calSel={y:now.getFullYear(),mo:now.getMonth(),d:now.getDate()};}var y=ST.calSel.y,mo=ST.calSel.mo;var bt=$("bilan-title");if(bt)bt.textContent=ST.calSel.d+" "+MONTHS_MIN[mo]+" "+y;var sh=document.querySelector("#view-journal .sec-head.sticky span:last-child");if(sh)sh.textContent="Notes de "+MONTHS_MIN[mo];renderEncours();var feed=[];ST.entries.forEach(function(en){(en.journal||[]).forEach(function(x,idx){var t=x.at?new Date(x.at):null;if(t&&t.getFullYear()===y&&t.getMonth()===mo)feed.push({e:en,x:x,idx:idx,at:x.at||0});});});feed.sort(function(a,b){return b.at-a.at;});var f=$("j-feed");if(!f)return;f.innerHTML="";if(!feed.length)f.appendChild(emptyBox("book-open","Aucune entrée ce jour-ci."));feed.slice(0,80).forEach(function(it){var item=el("div","jentry");var pd=el("div","poster");var pi=el("img");pi.src=it.e.posterThumb||it.e.posterUrl||NO_POSTER;pd.appendChild(pi);pd.addEventListener("click",function(ev){ev.stopPropagation();showCollectionDetail(it.e);});item.appendChild(pd);var b=el("div","content");b.appendChild(el("div","time",esc(entryTag(it.x))));var tx=el("div","text",esc(truncate(it.x.text||"",90)));tx.addEventListener("click",function(ev){ev.stopPropagation();openReaderForEntry(it.e,it.idx);});b.appendChild(tx);b.appendChild(el("div","title",esc(it.e.titre)));item.appendChild(b);var acts=el("div","acts");var ed=el("button");ed.setAttribute("aria-label","Modifier");ed.innerHTML='<span class="ic">'+ic("pen")+"</span>";ed.addEventListener("click",function(ev){ev.stopPropagation();quickNoteOpen(it.e,it.x.text,it.x.kind,it.idx,{kind:"entry",e:it.e});});var dl=el("button","del");dl.setAttribute("aria-label","Supprimer");dl.innerHTML='<span class="ic">'+ic("trash-2")+"</span>";dl.addEventListener("click",function(ev){ev.stopPropagation();showConfirm("Supprimer cette entrée ?","",function(){it.e.journal.splice(it.idx,1);dbPut(it.e).then(function(){toast("Entrée supprimée");refreshAll();});},"trash-2");});acts.appendChild(ed);acts.appendChild(dl);item.appendChild(acts);item.addEventListener("click",function(){openReaderForEntry(it.e,it.idx);});f.appendChild(item);});}
function injectFloatingNoteBtn(){if($("fab-note"))return;var b=el("button","fab-note hidden");b.id="fab-note";b.setAttribute("aria-label","Note rapide");b.innerHTML='<span class="ic">'+ic("notebook-pen")+"</span>";b.addEventListener("click",function(){quickNoteOpen(null,"","time",null,{kind:"global"});});document.body.appendChild(b);}
function updateFabVisibility(){var b=$("fab-note");if(b)b.classList.toggle("hidden",ST.view!=="journal");}
function injectBackupBanner(){var s=settingsLoad();var days=s.alertBackupDays||14;var last=parseInt(localStorage.getItem("last_gh_backup")||localStorage.getItem("last_backup")||"0",10);var main=document.querySelector("main");if(!main)return;var old=$("backup-banner");if(old)old.remove();if(sessionStorage.getItem("bb_dismissed")==="1")return;var age=last?(Date.now()-last)/86400000:9999;if(age<days)return;var b=el("div","backup-banner");b.id="backup-banner";b.innerHTML='<span class="ic">'+ic("alert")+"</span><span>Ça fait "+(last?Math.floor(age)+" jour(s)":"toujours")+" sans sauvegarde. Pense à exporter.</span>";var go=el("button","","<span>Sauvegarder</span>");go.addEventListener("click",function(){openOptSave();});var cl=el("button","bb-close");cl.setAttribute("aria-label","Ignorer");cl.innerHTML='<span class="ic">'+ic("x")+"</span>";cl.addEventListener("click",function(){sessionStorage.setItem("bb_dismissed","1");b.remove();});b.appendChild(go);b.appendChild(cl);main.insertBefore(b,main.firstChild);}

function renderOptions(){var grid=$("opt-grid");if(!grid)return;grid.innerHTML="";[{icon:"save",label:"Sauvegarde",fn:openOptSave},{icon:"list",label:"Mes listes",fn:openOptMyLists},{icon:"palette",label:"Apparence",fn:openOptAppearance},{icon:"bar-chart-3",label:"Stats",fn:openOptStats},{icon:"search",label:"Recherche",fn:openOptSearch},{icon:"smartphone",label:"Application",fn:openOptApp},{icon:"info",label:"À propos",fn:openOptAbout},{icon:"alert",label:"Danger",fn:openOptDanger}].forEach(function(cat){var b=el("button","opt-btn");b.innerHTML='<span class="ic">'+ic(cat.icon)+"</span><span>"+esc(cat.label)+"</span>";b.addEventListener("click",cat.fn);grid.appendChild(b);});}
function openOptSave(){var b=el("div");b.appendChild(el("div","sec-title","Sauvegarde locale"));b.appendChild(btn("Exporter en JSON","download","wide",function(){exportJSON();}));b.appendChild(btn("Importer (fusion)","upload","wide",function(){importJSON();}));b.appendChild(btn("Copier tout (TSV)","clipboard-copy","wide",function(){copyTSV();}));b.appendChild(el("div","sec-title","Backup GitHub (repo privé)"));var go=el("input");go.placeholder="Owner (ex : BoraGooum)";go.value=localStorage.getItem("gh_owner")||"";go.style.marginBottom="10px";b.appendChild(go);var gr=el("input");gr.placeholder="Repo (ex : collection-backup)";gr.value=localStorage.getItem("gh_repo")||"";gr.style.marginBottom="10px";b.appendChild(gr);var gt=el("input");gt.placeholder="Token (github_pat_…)";gt.type="password";gt.value=localStorage.getItem("gh_token")||"";gt.style.marginBottom="14px";b.appendChild(gt);b.appendChild(btn("Sauver la config","save","primary wide",function(){localStorage.setItem("gh_owner",go.value.trim());localStorage.setItem("gh_repo",gr.value.trim());localStorage.setItem("gh_token",gt.value.trim());toast("Config GitHub sauvée");}));b.appendChild(btn("Tester la connexion","link","wide",function(){ghTest();}));b.appendChild(btn("Sauvegarder maintenant","upload","wide",function(){ghBackupNow(true);}));b.appendChild(btn("Restaurer depuis GitHub","download","wide",function(){showConfirm("Restaurer ?","Les œuvres manquantes seront ajoutées.",function(){ghRestore();},"Restaurer");}));var lb=localStorage.getItem("last_gh_backup");b.appendChild(el("div","","Dernier backup GitHub : <b>"+(lb?new Date(parseInt(lb,10)).toLocaleString("fr-FR"):"jamais")+"</b>"));setModal("Sauvegarde",b,[["Fermer","",closeModal,"x"]]);}
function openOptMyLists(){var body=el("div");var tabs=el("div","chips mylist-tabs");var host=el("div");var cur="plateformes";var LABELS={types:"Types",plateformes:"Plateformes",supports:"Supports",packagings:"Packagings",bonus:"Bonus"};function usedCount(key,name){var n=0;ST.entries.forEach(function(e){if(key==="types"&&e.type===name)n++;if(key==="plateformes"&&e.plateforme===name)n++;if(key==="supports"&&e.support===name)n++;if(key==="packagings"&&e.packaging===name)n++;if(key==="bonus"&&(e.bonus||[]).indexOf(name)>=0)n++;});return n;}function renderTabs(){tabs.innerHTML="";LIST_KEYS.forEach(function(k){var c=el("div","chip"+(k===cur?" on":""),"<span>"+LABELS[k]+"</span>");c.addEventListener("click",function(){cur=k;renderTabs();renderRows();});tabs.appendChild(c);});}function renderRows(){host.innerHTML="";var items=listItems(cur);if(!items.length){host.appendChild(emptyBox("list","Liste vide."));return;}items.forEach(function(it,i){var row=el("div","mylist-row");row.innerHTML=valueIconHTML(it)+'<span class="ml-name">'+esc(it.name)+"</span>"+(it.base?'<span class="ml-base">base</span>':"");var used=usedCount(cur,it.name);if(used)row.querySelector(".ml-name").insertAdjacentHTML("afterend",' <span class="ml-used">utilisée ('+used+")</span>");var up=el("button","sq-btn ml-btn");up.setAttribute("aria-label","Monter");up.innerHTML='<span class="ic">'+ic("arrow-up")+"</span>";up.disabled=(i===0);up.addEventListener("click",function(){moveItem(cur,it.name,"up");renderRows();});var dn=el("button","sq-btn ml-btn");dn.setAttribute("aria-label","Descendre");dn.innerHTML='<span class="ic">'+ic("arrow-down")+"</span>";dn.disabled=(i===items.length-1);dn.addEventListener("click",function(){moveItem(cur,it.name,"down");renderRows();});var edit=el("button","sq-btn ml-btn");edit.setAttribute("aria-label","Personnaliser");edit.innerHTML='<span class="ic">'+ic("palette")+"</span>";edit.addEventListener("click",function(){openItemEditor(cur,it,renderRows);});row.appendChild(up);row.appendChild(dn);row.appendChild(edit);if(!it.base){var del=el("button","sq-btn ml-btn del");del.setAttribute("aria-label","Supprimer");del.innerHTML='<span class="ic">'+ic("trash")+"</span>";del.addEventListener("click",function(){if(used)showConfirm("« "+it.name+" » est utilisée par "+used+" œuvre(s).","Elle restera sur ces œuvres mais disparaîtra des futurs choix.",function(){removeCustom(cur,it.name);renderRows();},"Supprimer quand même");else{removeCustom(cur,it.name);renderRows();}});row.appendChild(del);}host.appendChild(row);});}body.appendChild(tabs);body.appendChild(host);renderTabs();renderRows();setModal("Mes listes",body,[["Fermer","",closeModal,"x"]]);}
function openItemEditor(key,item,after){var state={view:"main",q:""};function fresh(){return listItems(key).filter(function(x){return x.name===item.name;})[0]||item;}function renderMain(){var it=fresh();var b=el("div");var nf=el("div","field");nf.appendChild(el("span","flabel","Nom"));var ni=el("input");ni.value=it.name;ni.disabled=!!it.base;if(it.base)ni.title="Valeur de base : nom non modifiable.";nf.appendChild(ni);b.appendChild(nf);var ib=btn("Icône : "+(it.icon||"tag"),it.icon||"tag","wide",function(){state.view="icon";render();});b.appendChild(ib);var cb=btn("Couleur : "+(it.color?"définie":"aucune"),"palette","wide",function(){state.view="color";render();});b.appendChild(cb);if(!it.base){var rb=btn("Renommer","pen","wide",function(){var v=ni.value.trim();if(!v||v===it.name)return;var used=0;ST.entries.forEach(function(e){if(key==="types"&&e.type===it.name)used++;if(key==="plateformes"&&e.plateforme===it.name)used++;if(key==="supports"&&e.support===it.name)used++;if(key==="packagings"&&e.packaging===it.name)used++;if(key==="bonus"&&(e.bonus||[]).indexOf(it.name)>=0)used++;});var doRename=function(){renameItem(key,it.name,v);var saves=[];ST.entries.forEach(function(e){if(key==="types"&&e.type===it.name){e.type=v;saves.push(dbPut(e));}if(key==="plateformes"&&e.plateforme===it.name){e.plateforme=v;saves.push(dbPut(e));}if(key==="supports"&&e.support===it.name){e.support=v;saves.push(dbPut(e));}if(key==="packagings"&&e.packaging===it.name){e.packaging=v;saves.push(dbPut(e));}if(key==="bonus"){var bx=e.bonus||[];var bi=bx.indexOf(it.name);if(bi>=0){bx[bi]=v;e.bonus=bx;saves.push(dbPut(e));}}});Promise.all(saves).then(function(){toast("Renommé"+(used?" ("+used+" œuvre(s) mise(s) à jour)":""));after();refreshAll();});};if(used)showConfirm("Renommer ?","« "+it.name+" » est utilisé par "+used+" œuvre(s). Elles suivront le nouveau nom.",doRename,"Renommer");else doRename();});b.appendChild(rb);}setSheet("Personnaliser : "+it.name,b,[["Fermer","",closeMenu,"x"]]);}
function renderIcon(){var it=fresh();var b=el("div");var search=el("input");search.placeholder="Chercher une icône (ex : manette)…";search.value=state.q;search.style.marginBottom="14px";b.appendChild(search);var grid=el("div","icon-grid");b.appendChild(grid);function cell(name,svg){var c=el("button","icon-cell"+(name===it.icon?" on":""));c.setAttribute("aria-label","Icône "+name);c.innerHTML=svg||ic(name);c.addEventListener("click",function(){setItemMeta(key,it.name,{icon:name});after();state.view="main";render();});return c;}function renderBase(){grid.innerHTML="";Object.keys(I).forEach(function(n){grid.appendChild(cell(n,I[n]));});}function renderSearch(q){grid.innerHTML="";var names=LUCIDE_NAMES.filter(function(n){return n.indexOf(q)>=0;}).slice(0,60);if(!names.length){grid.appendChild(el("div","status","Aucune icône trouvée."));return;}names.forEach(function(n){if(I[n]){grid.appendChild(cell(n,I[n]));return;}var c=el("button","icon-cell"+(n===it.icon?" on":""));c.setAttribute("aria-label","Charger icône "+n);c.innerHTML='<span class="ic">'+ic("image")+"</span>";c.addEventListener("click",function(){fetch("https://unpkg.com/lucide-static@latest/icons/"+n+".svg").then(function(r){return r.text();}).then(function(txt){localStorage.setItem("icon_svg_"+n,txt);I[n]=txt;setItemMeta(key,it.name,{icon:n});after();state.view="main";render();}).catch(function(){toast("Icône indisponible (réseau).",3000);});});grid.appendChild(c);});}search.addEventListener("input",function(){state.q=norm(search.value);if(!state.q)renderBase();else renderSearch(state.q);});if(!state.q)renderBase();else renderSearch(state.q);setSheet("Icône",b,[["Retour","",function(){state.view="main";render();},"x"]]);}
function renderColor(){var it=fresh();var b=el("div","color-grid");var none=el("button","color-cell"+(!it.color?" on":""));none.setAttribute("aria-label","Aucune couleur");none.style.background="var(--s2)";none.innerHTML='<span class="ic">'+ic("x")+"</span>";none.addEventListener("click",function(){setItemMeta(key,it.name,{color:null});after();state.view="main";render();});b.appendChild(none);COLOR_SWATCHES.forEach(function(hex){var c=el("button","color-cell"+(hex===it.color?" on":""));c.setAttribute("aria-label","Couleur "+hex);c.style.background=hex;c.addEventListener("click",function(){setItemMeta(key,it.name,{color:hex});after();state.view="main";render();});b.appendChild(c);});setSheet("Couleur",b,[["Retour","",function(){state.view="main";render();},"x"]]);}
function render(){if(state.view==="icon")renderIcon();else if(state.view==="color")renderColor();else renderMain();}render();}
function openOptAppearance(){var s=settingsLoad();var b=el("div");b.appendChild(el("span","flabel","Couleur du thème"));var swr=el("div","swatch-row");THEME_PRESETS.forEach(function(t){var sw=el("div","swatch"+(t.id===s.theme?" on":""));sw.style.background="linear-gradient(135deg,"+t.acc+","+t.acc2+")";sw.title=t.name;sw.innerHTML='<span class="ck"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round"><polyline points="20 6 9 17 4 12"/></svg></span>';sw.addEventListener("click",function(){s.theme=t.id;settingsSave(s);applyTheme(t.id);closeModal();openOptAppearance();});swr.appendChild(sw);});b.appendChild(swr);b.appendChild(el("span","flabel","Police d'écriture"));FONT_PRESETS.forEach(function(f){ensureFontLoaded(f.id);});var fl=el("div","radio-list");FONT_PRESETS.forEach(function(f){var o=el("div","radio-opt"+(f.id===s.font?" sel":""));o.innerHTML='<span class="dot"></span><span class="lbl" style="font-family:'+f.stack+';font-size:17px;">'+esc(f.name)+"</span>";o.addEventListener("click",function(){s.font=f.id;s.fontTitle=f.id;settingsSave(s);applyFont(f.id);applyTitleFont(f.id);closeModal();openOptAppearance();});fl.appendChild(o);});b.appendChild(fl);b.appendChild(el("span","flabel","Taille du texte"));var fp=el("div","pill-sel");[["s","Petit"],["m","Normal"],["l","Grand"]].forEach(function(o){var x=el("button",o[0]===s.fontSize?"on":"","<span>"+o[1]+"</span>");x.addEventListener("click",function(){s.fontSize=o[0];settingsSave(s);applySettings();closeModal();openOptAppearance();});fp.appendChild(x);});b.appendChild(fp);b.appendChild(el("span","flabel","Densité"));var dp=el("div","pill-sel");[["comfort","Confort"],["compact","Compact"]].forEach(function(o){var x=el("button",o[0]===s.density?"on":"","<span>"+o[1]+"</span>");x.addEventListener("click",function(){s.density=o[0];settingsSave(s);applySettings();closeModal();openOptAppearance();});dp.appendChild(x);});b.appendChild(dp);setModal("Apparence",b,[["Fermer","",closeModal,"x"]]);}
function openOptStats(){var b=el("div");var entries=ST.entries,total=entries.length,byType={},sum=0,cnt=0,coeurs=0;entries.forEach(function(e){byType[e.type]=(byType[e.type]||0)+1;if(e.note!=null){sum+=e.note;cnt++;}if(e.coeur)coeurs++;});var sec=el("div","box");sec.appendChild(el("div","sec-title","Par type"));Object.keys(byType).forEach(function(t){var r=el("div","sline");r.innerHTML="<span>"+esc(t)+"</span><b>"+byType[t]+"</b>";sec.appendChild(r);});b.appendChild(sec);var sec2=el("div","box");sec2.appendChild(el("div","sec-title","Notes"));var r2=el("div","sline");r2.innerHTML="<span>Moyenne</span><b>"+(cnt?(sum/cnt).toFixed(1):"—")+"/10</b>";sec2.appendChild(r2);var r3=el("div","sline");r3.innerHTML="<span>Total œuvres</span><b>"+total+"</b>";sec2.appendChild(r3);var r4=el("div","sline");r4.innerHTML="<span>Coups de cœur</span><b>"+coeurs+"</b>";sec2.appendChild(r4);b.appendChild(sec2);setModal("Statistiques",b,[["Fermer","",closeModal,"x"]]);}
function openOptSearch(){var s=settingsLoad();var b=el("div");b.appendChild(el("span","flabel","Type par défaut"));var tp=el("div","pill-sel");allTypes().forEach(function(t){var x=el("button",t===s.defaultType?"on":"","<span>"+esc(t)+"</span>");x.addEventListener("click",function(){s.defaultType=t;settingsSave(s);ST.currentType=t;closeModal();openOptSearch();buildTypeDropdown();});tp.appendChild(x);});b.appendChild(tp);setModal("Recherche",b,[["Fermer","",closeModal,"x"]]);}
function openOptApp(){var b=el("div");b.appendChild(btn("Installer l'application","download","wide",function(){triggerInstall();}));b.appendChild(btn("Vider le cache hors-ligne","trash","wide",function(){if("caches"in window)caches.keys().then(function(k){k.forEach(function(x){caches.delete(x);});});toast("Cache vidé");}));b.appendChild(el("div","","Réseau : <b>"+(navigator.onLine?"connecté":"hors-ligne")+"</b>"));setModal("Application",b,[["Fermer","",closeModal,"x"]]);}
function openOptAbout(){var b=el("div");b.appendChild(el("div","","Version : <b>V0.9.3</b>"));b.appendChild(el("div","","Build : <b>"+new Date(BUILD).toLocaleString("fr-FR",{timeZone:"Europe/Paris"})+"</b>"));var c=el("a","","Créé par Gooumbora");c.href="https://www.senscritique.com/Gooumbora";c.target="_blank";c.style.color="var(--acc)";b.appendChild(c);setModal("À propos",b,[["Fermer","",closeModal,"x"]]);}
function openOptDanger(){var b=el("div");b.appendChild(btn("Effacer toutes mes œuvres","trash","wide",function(){showConfirm("Effacer TOUTES tes œuvres ?","Cette action est irréversible.",function(){(async function(){for(var i=0;i<ST.entries.length;i++)await dbDelete(ST.entries[i].id);refreshAll();toast("Vidé");})();},"Effacer");}));b.appendChild(btn("Réinitialiser les réglages","rotate-ccw","wide",function(){showConfirm("Remettre les réglages par défaut ?","",function(){localStorage.removeItem("settings");settingsSave(Object.assign({},SETTINGS_DEFAULTS));applySettings();toast("Réglages réinitialisés");},"Réinitialiser");}));setModal("Danger",b,[["Fermer","",closeModal,"x"]]);}

function ghConfig(){return{owner:(localStorage.getItem("gh_owner")||"").trim(),repo:(localStorage.getItem("gh_repo")||"").trim(),token:(localStorage.getItem("gh_token")||"").trim()};}
function ghB64encode(s){return btoa(unescape(encodeURIComponent(s)));}
function ghB64decode(s){return decodeURIComponent(escape(atob(s)));}
async function ghGetFile(c,path){var r=await fetch("https://api.github.com/repos/"+c.owner+"/"+c.repo+"/contents/"+path,{headers:{Authorization:"Bearer "+c.token,Accept:"application/vnd.github+json"}});if(r.status===404)return null;if(!r.ok)throw new Error("GET "+r.status);return await r.json();}
async function ghPutFile(c,path,content){var cur=await ghGetFile(c,path);var body={message:"Backup auto "+new Date().toISOString(),content:ghB64encode(content)};if(cur&&cur.sha)body.sha=cur.sha;var r=await fetch("https://api.github.com/repos/"+c.owner+"/"+c.repo+"/contents/"+path,{method:"PUT",headers:{Authorization:"Bearer "+c.token,Accept:"application/vnd.github+json","Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error("PUT "+r.status);return await r.json();}
var ghTimer=null;
function scheduleGitHubBackup(){var c=ghConfig();if(!c.owner||!c.repo||!c.token)return;if(ghTimer)clearTimeout(ghTimer);ghTimer=setTimeout(function(){ghBackupNow(false);},5000);}
function dumpLists(){var o={};LIST_KEYS.forEach(function(k){o[k]=getList(k);});return o;}
async function ghBackupNow(manual){var c=ghConfig();if(!c.owner||!c.repo||!c.token){if(manual)toast("Configure GitHub dans Options.");return;}var data={version:"V0.9.3",exportDate:new Date().toISOString(),settings:settingsLoad(),lists:dumpLists(),customIcons:getCustomIcons(),entries:ST.entries};try{await ghPutFile(c,"sauvegarde.json",JSON.stringify(data));localStorage.setItem("last_gh_backup",String(Date.now()));if(manual)toast("Sauvegarde GitHub OK");}catch(e){if(manual)toast("Erreur GitHub : "+e.message,3000);}}
async function ghTest(){var c=ghConfig();if(!c.owner||!c.repo||!c.token){toast("Remplis owner, repo et token.");return;}try{var r=await fetch("https://api.github.com/repos/"+c.owner+"/"+c.repo,{headers:{Authorization:"Bearer "+c.token,Accept:"application/vnd.github+json"}});if(r.ok){var d=await r.json();toast("Connexion OK : "+d.full_name+(d.private?" (privé)":" (PUBLIC !)"));}else toast("Erreur "+r.status,3000);}catch(e){toast("Réseau impossible",3000);}}
async function ghRestore(){var c=ghConfig();if(!c.owner||!c.repo||!c.token){toast("Configure GitHub dans Options.");return;}try{var f=await ghGetFile(c,"sauvegarde.json");if(!f){toast("Aucune sauvegarde trouvée.",3000);return;}var data=JSON.parse(ghB64decode(f.content));var list=data.entries||[],ids={};ST.entries.forEach(function(x){ids[x.id]=1;});var added=0;for(var i=0;i<list.length;i++){var en=list[i];if(en&&en.id&&!ids[en.id]){if(!en.titre)en.titre="Sans titre";if(!en.dateAjout)en.dateAjout=new Date().toISOString();await dbPut(en);added++;}}if(data.settings)settingsSave(Object.assign({},SETTINGS_DEFAULTS,data.settings));if(data.lists)LIST_KEYS.forEach(function(k){if(Array.isArray(data.lists[k])&&data.lists[k].length)setList(k,data.lists[k]);});if(data.customTypes)importLegacyList("types",data.customTypes);if(data.customLists){importLegacyList("plateformes",data.customLists.plateformes);importLegacyList("supports",data.customLists.supports);importLegacyList("packagings",data.customLists.packagings);importLegacyList("bonus",data.customLists.bonus);}if(data.customIcons)setCustomIcons(data.customIcons);applySettings();buildTypeDropdown();refreshAll();toast("Restauré : "+added+" œuvre(s) ajoutée(s)");}catch(e){toast("Restauration impossible : "+e.message,3000);}}